services:

  app:
    build: 
      context: ./docker/php-fpm

    container_name: symfonyApp
    restart: unless-stopped
    volumes:
      - ./:/var/www/shop_wine
    environment:
      - APP_ENV=prod

    expose:
      - 9000

    depends_on:
      - db

  web:
    image: nginx:1.26.0-alpine
    container_name: nginx_server
    restart: unless-stopped
    volumes:
      - ./:/var/www/shop_wine
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - '8082:80'

    depends_on:
      - app
    

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/var/www/shop_wine

  #   ports:
  #     - '8081:8080'

  
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80

    volumes:
      - ./:/var/www/shop_wine


  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: symfonyboutique
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: ''

    ports:
      - '3307:3306'

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    
